services:
  - type: worker
    name: mafia-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: MAFIA_BOT_TOKEN
        sync: false
      - key: BB_API_URL
        sync: false
      - key: BB_API_KEY
        sync: false
